export const FETCH_MARSPHOTOS_SUCCESS = 'FETCH_MARSPHOTOS_SUCCESS'
export const FETCH_MARSPHOTOS_FAILED = 'FETCH_MARSPHOTOS_FAILED'
export const FETCH_MARSPHOTO_BY_ID = 'FETCH_MARSPHOTO_BY_ID'
export const REMOVE_MARSPHOTO_MODAL = 'REMOVE_MARSPHOTO_MODAL'